# Generated by Django 6.0.2 on 2026-03-12 10:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restocktodo',
            name='estimated_cost_per_unit',
            field=models.DecimalField(decimal_places=0, help_text='Estimated cost price per unit in XAF', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='restocktodo',
            name='quantity_needed',
            field=models.IntegerField(help_text='Number of units to restock', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
