# Generated by Django 6.0.2 on 2026-02-21 07:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(help_text='Number of units sold', validators=[django.core.validators.MinValueValidator(1)])),
                ('selling_price_at_time', models.DecimalField(decimal_places=2, help_text='Selling price per unit at the time of sale', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total sale amount (selling_price × quantity)', max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, help_text='Profit from this sale ((selling_price - cost_price) × quantity)', max_digits=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of sale')),
                ('product', models.ForeignKey(help_text='Product that was sold', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-sale_date'],
            },
        ),
    ]
