# Generated by Django 6.0.2 on 2026-03-12 10:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(decimal_places=0, help_text='Profit in XAF from this sale ((selling_price - cost_price) × quantity)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='selling_price_at_time',
            field=models.DecimalField(decimal_places=0, help_text='Selling price per unit in XAF at the time of sale', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, help_text='Total sale amount in XAF (selling_price × quantity)', max_digits=10),
        ),
    ]
