# Generated by Django 6.0.2 on 2026-02-21 07:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Product name (e.g., 'Rose Lipstick - Shade 12')", max_length=200)),
                ('category', models.CharField(help_text="Product category (e.g., 'Lipstick', 'Foundation', 'Mascara')", max_length=100)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Cost price per unit (what you paid to buy this product)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit (what customers pay)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity_in_stock', models.IntegerField(default=0, help_text='Current number of units in stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Alert when stock falls to this number or below', validators=[django.core.validators.MinValueValidator(0)])),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='When this product was first added')),
                ('last_restocked_date', models.DateField(blank=True, help_text='Last time stock was replenished', null=True)),
                ('supplier_name', models.CharField(blank=True, help_text='Name of supplier (optional)', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-date_added'],
            },
        ),
    ]
