# Generated by Django 6.0.2 on 2026-03-12 10:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_create_megaglow_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, help_text='Cost price per unit in XAF (what you paid to buy this product)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=0, help_text='Selling price per unit in XAF (what customers pay)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
    ]
